"""create medition models

Revision ID: 07a0cfdd4436
Revises: 111551b33dbf
Create Date: 2026-06-13 16:00:05.524146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07a0cfdd4436'
down_revision = '111551b33dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mediciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planta_id', sa.Integer(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('humedad', sa.Float(), nullable=False),
    sa.Column('desarrollo', sa.Float(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['planta_id'], ['plantas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.SMALLINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('tag', sa.TEXT(), server_default=sa.text("'PLANT001'::text"), autoincrement=False, nullable=False),
    sa.Column('species', sa.TEXT(), server_default=sa.text("'Frailejón'::text"), autoincrement=False, nullable=True),
    sa.Column('germination_date', sa.DATE(), server_default=sa.text("'2023-09-27'::date"), autoincrement=False, nullable=True),
    sa.Column('initial_conditions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'tag', name=op.f('plantas_pkey')),
    comment='de'
    )
    op.create_table('plant_humidity_records',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('species', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('humedad', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('plant_humidity_records_pkey')),
    comment='Almacena los niveles de humedad registrados para cada especie vegetal. Estos datos permiten analizar las condiciones ambientales asociadas al crecimiento y la salud de las plantas.'
    )
    op.create_table('plant_growth_records',
    sa.Column('species', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('germination_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('temperatura', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('humedad', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('desarrollo_por_mes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    comment='Registra las mediciones ambientales y el progreso de desarrollo de las plantas a lo largo del tiempo. Incluye la especie, fecha de germinación, condiciones actuales de temperatura y humedad, así como un historial mensual del porcentaje o nivel de desarrollo de cada planta.'
    )
    op.drop_table('mediciones')
    # ### end Alembic commands ###
