"""medicion planta

Revision ID: 0fe1ebce907a
Revises: af9e9ff1d1df
Create Date: 2026-07-09 12:37:34.934750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe1ebce907a'
down_revision = 'af9e9ff1d1df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediciones', schema=None) as batch_op:
        batch_op.drop_column('desarrollo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desarrollo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
