"""create plantas table

Revision ID: 111551b33dbf
Revises: 
Create Date: 2026-06-13 15:36:16.039701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '111551b33dbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():

    op.create_table(
        'plantas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tag', sa.String(length=50), nullable=False),
        sa.Column('species', sa.String(length=100), nullable=False),
        sa.Column('germination_date', sa.Date(), nullable=False),
        sa.Column('initial_conditions', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_humidity_records',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('species', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('humedad', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('plant_humidity_records_pkey')),
    comment='Almacena los niveles de humedad registrados para cada especie vegetal. Estos datos permiten analizar las condiciones ambientales asociadas al crecimiento y la salud de las plantas.'
    )
    op.create_table('plant_growth_records',
    sa.Column('species', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('germination_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('temperatura', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('humedad', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('desarrollo_por_mes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    comment='Registra las mediciones ambientales y el progreso de desarrollo de las plantas a lo largo del tiempo. Incluye la especie, fecha de germinación, condiciones actuales de temperatura y humedad, así como un historial mensual del porcentaje o nivel de desarrollo de cada planta.'
    )
    op.create_table('plants',
    sa.Column('id', sa.SMALLINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('tag', sa.TEXT(), server_default=sa.text("'PLANT001'::text"), autoincrement=False, nullable=False),
    sa.Column('species', sa.TEXT(), server_default=sa.text("'Frailejón'::text"), autoincrement=False, nullable=True),
    sa.Column('germination_date', sa.DATE(), server_default=sa.text("'2023-09-27'::date"), autoincrement=False, nullable=True),
    sa.Column('initial_conditions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'tag', name=op.f('plantas_pkey')),
    comment='de'
    )
    op.drop_table('plantas')
    # ### end Alembic commands ###
