"""medicion planta table

Revision ID: 1dbe6ceed474
Revises: 0fe1ebce907a
Create Date: 2026-07-09 14:16:11.270445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dbe6ceed474'
down_revision = '0fe1ebce907a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mediciones_planta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('planta_id', sa.Integer(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('diametro_tallo', sa.Float(), nullable=True),
    sa.Column('numero_hojas', sa.Integer(), nullable=True),
    sa.Column('numero_flores', sa.Integer(), nullable=True),
    sa.Column('numero_frutos', sa.Integer(), nullable=True),
    sa.Column('desarrollo', sa.Float(), nullable=True),
    sa.Column('humedad_sustrato', sa.Float(), nullable=True),
    sa.Column('salud', sa.String(length=20), nullable=True),
    sa.Column('color_hojas', sa.String(length=30), nullable=True),
    sa.Column('plagas', sa.Boolean(), nullable=True),
    sa.Column('enfermedad', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['planta_id'], ['plantas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mediciones_planta')
    # ### end Alembic commands ###
