"""photo especie

Revision ID: 1f077c8042bc
Revises: 1dbe6ceed474
Create Date: 2026-07-09 20:37:26.867373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f077c8042bc'
down_revision = '1dbe6ceed474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('especies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('especies', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
