"""locations medition

Revision ID: 257d37882cd8
Revises: 5c04a10f334b
Create Date: 2026-07-08 11:40:05.144405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257d37882cd8'
down_revision = '5c04a10f334b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ideal_temperature_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ideal_temperature_max', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ideal_humidity_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ideal_humidity_max', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('plants_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('species_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('health_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('profile_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('profile_updated_at')
        batch_op.drop_column('health_status')
        batch_op.drop_column('species_count')
        batch_op.drop_column('plants_count')
        batch_op.drop_column('ideal_humidity_max')
        batch_op.drop_column('ideal_humidity_min')
        batch_op.drop_column('ideal_temperature_max')
        batch_op.drop_column('ideal_temperature_min')

    # ### end Alembic commands ###
