"""change expected_growth_rate to string

Revision ID: 39eeefced017
Revises: 7a28598b2ed7
Create Date: 2026-06-17 20:05:02.595281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39eeefced017'
down_revision = '7a28598b2ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('especies', schema=None) as batch_op:
        batch_op.alter_column('expected_growth_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('especies', schema=None) as batch_op:
        batch_op.alter_column('expected_growth_rate',
               existing_type=sa.String(length=50),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    # ### end Alembic commands ###
