"""lazy medicion locations

Revision ID: 5c04a10f334b
Revises: 39eeefced017
Create Date: 2026-06-25 13:03:20.923392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c04a10f334b'
down_revision = '39eeefced017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('mediciones_planta_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'locations', ['location_id'], ['id'])
        batch_op.drop_column('planta_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planta_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mediciones_planta_id_fkey'), 'plantas', ['planta_id'], ['id'])
        batch_op.drop_column('location_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
