"""initial schema

Revision ID: 6681f12250c7
Revises: 
Create Date: 2026-06-15 17:28:39.156323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6681f12250c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('species', sa.String(length=100), nullable=False),
    sa.Column('germination_date', sa.Date(), nullable=False),
    sa.Column('initial_conditions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mediciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planta_id', sa.Integer(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('humedad', sa.Float(), nullable=False),
    sa.Column('desarrollo', sa.Float(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['planta_id'], ['plantas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mediciones')
    op.drop_table('plantas')
    # ### end Alembic commands ###
