"""medicion satus

Revision ID: af9e9ff1d1df
Revises: 257d37882cd8
Create Date: 2026-07-08 20:30:11.721333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9e9ff1d1df'
down_revision = '257d37882cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediciones', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
