"""add column in plantas and add table especies

Revision ID: faa9c5ea9d2c
Revises: 6681f12250c7
Create Date: 2026-06-16 14:11:44.676913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa9c5ea9d2c'
down_revision = '6681f12250c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ideal_humidity_min', sa.Float(), nullable=True),
    sa.Column('ideal_humidity_max', sa.Float(), nullable=True),
    sa.Column('ideal_temperature_min', sa.Float(), nullable=True),
    sa.Column('ideal_temperature_max', sa.Float(), nullable=True),
    sa.Column('expected_growth_rate', sa.Float(), nullable=True),
    sa.Column('average_germination_days', sa.Integer(), nullable=True),
    sa.Column('average_transplant_days', sa.Integer(), nullable=True),
    sa.Column('sunlight_requirement', sa.String(length=50), nullable=True),
    sa.Column('watering_frequency_days', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('plantas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('common_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('variety', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('especie_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['tag'])
        batch_op.create_foreign_key(None, 'especies', ['especie_id'], ['id'])
        batch_op.drop_column('species')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('especie_id')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('location')
        batch_op.drop_column('status')
        batch_op.drop_column('variety')
        batch_op.drop_column('common_name')

    op.drop_table('especies')
    # ### end Alembic commands ###
